config/routes.rb
AppEmployee::Application.routes.draw do
  get "employee_profiles/show"

  get "teams/new"

  get "teams/index"

  get "teams/show"

  get "teams/destroy"

  resources :employees
  resources :employee_profiles
  resources :teams
  
  root to: "employees#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :supervisor_id, :employee_profile_attributes, :team_ids,
                  :supervised_team_ids

  belongs_to :supervisor, :class_name => 'Employee'
  has_many :subordinates, :class_name => 'Employee'

  has_many :team_memberships

  has_many :teams, :through => :team_memberships
  
  has_many :supervised_teams, :class_name => "Team", :foreign_key => :supervisor_id, :inverse_of => :supervisor

  has_one :employee_profile, :inverse_of => :employee

  accepts_nested_attributes_for :employee_profile
end

app/models/employee_profile.rb
class EmployeeProfile < ActiveRecord::Base
  attr_accessible :name, :salary, :position, :email, :employee_id,
  				  :height, :favorite_food, :favorite_day, :birth_date, :age,
  				  :photo

  has_attached_file :photo
  belongs_to :employee, :class_name => "Employee", :inverse_of => :employee_profile
end

app/models/team.rb
class Team < ActiveRecord::Base
  #validate :has_a_team_member
  #validates :name, :presence => :true
  attr_accessible :supervisor_id, :name, :member_ids

  has_many :memberships, :class_name => "TeamMembership", :foreign_key => :team_id
  has_many :members, :through => :memberships, :source => :employee, :foreign_key => :employee_id

  belongs_to :supervisor, :class_name => "Employee", :inverse_of => :supervised_teams

  private
  def has_a_team_member
  	if members.empty?
  		errors[:base] << 'No members in team!'
  	end
  end
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  attr_accessible :employee_id, :team_id

  belongs_to :employee
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employee_profiles_controller.rb
class EmployeeProfilesController < ApplicationController
  def show
  	@profile = EmployeeProfile.find(params[:id])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
    @employee.build_employee_profile
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    employee = Employee.find(params[:id])
    if employee.update_attributes(params[:employee])
      flash[:success] = "Employee updated!"
      redirect_to employee.employee_profile
    else
      flash[:errors] = employee.errors.full_messages
      render :edit
    end
  end

  def create
    employee = Employee.new(params[:employee])
    if employee.save
      flash[:success] = "Employee created!"
      redirect_to employee.employee_profile
    else
      flash[:errors] = employee.errors.full_messages
      redirect_to new_employee_url
    end
  end

  def destroy
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def new
  	@team = Team.new
  end

  def index
  end

  def create
  	team = Team.new(params[:team])
    if team.save
      flash[:success] = "Team created!"
    else
      flash[:errors] = team.errors.full_messages
    end
    redirect_to teams_url
  end

  def show
  	@team = Team.find(params[:id])
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    team = Team.find(params[:id])
    if team.update_attributes(params[:team])
      flash[:success] = "Team updated!"
      redirect_to teams_url
    else
      flash[:errors] = team.errors.full_messages
      render :edit
    end
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_profiles_helper.rb
module EmployeeProfilesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/employee_profiles/show.html.erb
<h1> <%= @profile.name %>'s Details</h1>
<%= @profile.email %>

<h4> Supervisor: </h4>
<% if @profile.employee.supervisor.nil? %>
	None
<% else %>
	<%= @profile.employee.supervisor.employee_profile.name %>
<% end %>

<h4>Team Leader of:</h4>
<ul>
	<% @profile.employee.supervised_teams.each do |team| %>
		<li><%= team.name %></li>
	<% end %>
</ul>
<h3>Team Member of:</h3>
<ul>
	<% @profile.employee.teams.each do |team| %>
		<%= team.name %>
	<% end %>
</ul>

<h3>Position</h3>
<%= @profile.position %>

<h3>Salary</h3>
<%= sprintf("%.2f", @profile.salary) %>

<h3>Employee ID</h3>
<%= @profile.employee_id %>

<h3>Height</h3>
<%= @profile.height %>cm

<h3>Favorite Food</h3>
<%= @profile.favorite_food %>

<h3>Favorite Day</h3>
<%= @profile.favorite_day %>

<h3>Age</h3>
<%= @profile.age %>

<h3>Birth Date</h3>
<%= @profile.birth_date %>

<h3>Photo</h3>
<%= image_tag @profile.photo.url %>
<br><br>
<%= link_to "Edit Details", edit_employee_url(@profile.employee) %>

app/views/employees/_form.html.erb
<% all_employees = EmployeeProfile.all %>
<!-- action="/employees" method="post">
-->
<%= form_for(:employee) do |f| %>
	<p>Supervisor</p>
	<label>
		<select name="employee[supervisor_id]">
			<option value=''>None</option>
			<% all_employees.each do |emp| %>
				<% if @employee.supervisor == emp.employee %>			
					<option value=<%= emp.id %> selected><%=emp.name%></option>
				<% else %>
					<option value=<%= emp.id %>><%=emp.name%></option>
				<% end %>
			<% end %>
		</select>
	</label>

	<h4>Part of the following teams</h4>
	<% Team.all.each do |team| %>
		<label>
			<%= team.name %>
			<% if @employee.teams.include?(team) %>
				<input type="checkbox" name="employee[team_ids][]" value=<%= team.id %> checked>
			<% else %>
				<input type="checkbox" name="employee[team_ids][]" value=<%= team.id %> >
			<% end %>
		</label>
		<label> Team Leader
			<% if @employee.supervised_teams.include?(team) %>
				<input type="checkbox" name="employee[supervised_team_ids][]" value=<%= team.id %> checked>
			<% else %>
				<input type="checkbox" name="employee[supervised_team_ids][]" value=<%= team.id %>>
			<% end %>
		</label>
		<br><br>
	<% end %>

	<br><br>
	<label>
		Name
		<input type="text" name="employee[employee_profile_attributes][name]" value=<%= @employee.employee_profile.name %>>
	</label>

	<br><br>
	<label>
		E-mail
		<input type="text" name="employee[employee_profile_attributes][email]" value=<%= @employee.employee_profile.email %>>
	</label>

	<br><br>
	<label>
		Salary
		<input type="number" name="employee[employee_profile_attributes][salary]" value=<%= @employee.employee_profile.salary %>>
	</label>

	<br><br>
	<label>
		Height
		<input type="number" name="employee[employee_profile_attributes][height]" value=<%= @employee.employee_profile.height %>>
	</label>

	<br><br>
	<label>
		Favorite Food
		<input type="text" name="employee[employee_profile_attributes][favorite_food]" value=<%= @employee.employee_profile.favorite_food %>>
	</label>

	<br><br>
	<label>
		Favorite Day
		<input type="text" name="employee[employee_profile_attributes][favorite_day]" value=<%= @employee.employee_profile.favorite_day %>>
	</label>

	<br><br>
	<label>
		Age
		<input type="number" name="employee[employee_profile_attributes][age]" value=<%= @employee.employee_profile.age %>>
	</label>

	<br><br>
	
	<%= f.fields_for(:employee_profile) do |profile_form| %>
		<%=profile_form.label :birth_date %>
		<%=profile_form.date_select :birth_date, value: @employee.employee_profile.birth_date %>
	<% end %>
	<br><br>

	<%=f.submit %>
<% end %>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<h1>Edit <%= @employee.employee_profile.name %> Details</h1>
<% all_employees = EmployeeProfile.all %>
<!-- action="/employees" method="post">
-->
<%= form_for(@employee) do |f| %>
	<p>Supervisor</p>
	<label>
		<select name="employee[supervisor_id]">
			<option value=''>None</option>
			<% all_employees.each do |emp| %>
				<% if @employee.supervisor == emp.employee %>			
					<option value=<%= emp.id %> selected><%=emp.name%></option>
				<% else %>
					<option value=<%= emp.id %>><%=emp.name%></option>
				<% end %>
			<% end %>
		</select>
	</label>

	<h4>Part of the following teams</h4>
	<% Team.all.each do |team| %>
		<label>
			<%= team.name %>
			<% if @employee.teams.include?(team) %>
				<input type="checkbox" name="employee[team_ids][]" value=<%= team.id %> checked>
			<% else %>
				<input type="checkbox" name="employee[team_ids][]" value=<%= team.id %> >
			<% end %>
		</label>
		<label> Team Leader
			<% if @employee.supervised_teams.include?(team) %>
				<input type="checkbox" name="employee[supervised_team_ids][]" value=<%= team.id %> checked>
			<% else %>
				<input type="checkbox" name="employee[supervised_team_ids][]" value=<%= team.id %>>
			<% end %>
		</label>
		<br><br>
	<% end %>

	<br><br>
	<label>
		Name
		<input type="text" name="employee[employee_profile_attributes][name]" value=<%= @employee.employee_profile.name %>>
	</label>

	<br><br>
	<label>
		E-mail
		<input type="text" name="employee[employee_profile_attributes][email]" value=<%= @employee.employee_profile.email %>>
	</label>

	<br><br>
	<label>
		Salary
		<input type="number" name="employee[employee_profile_attributes][salary]" value=<%= @employee.employee_profile.salary %>>
	</label>

	<br><br>
	<label>
		Height
		<input type="number" name="employee[employee_profile_attributes][height]" value=<%= @employee.employee_profile.height %>>
	</label>

	<br><br>
	<label>
		Favorite Food
		<input type="text" name="employee[employee_profile_attributes][favorite_food]" value=<%= @employee.employee_profile.favorite_food %>>
	</label>

	<br><br>
	<label>
		Favorite Day
		<input type="text" name="employee[employee_profile_attributes][favorite_day]" value=<%= @employee.employee_profile.favorite_day %>>
	</label>

	<br><br>
	<label>
		Age
		<input type="number" name="employee[employee_profile_attributes][age]" value=<%= @employee.employee_profile.age %>>
	</label>

	<br><br>
	
	<%= f.fields_for(:employee_profile) do |profile_form| %>
		<%=profile_form.label :birth_date %>
		<%=profile_form.date_select :birth_date, value: @employee.employee_profile.birth_date %>
	<% end %>
	<br><br>

	<%=f.submit %>
<% end %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<ul>
	<% EmployeeProfile.all.each do |emp| %>
		<li><%= link_to "#{emp.name}", emp %></li>
	<% end %>
</ul>

<br><br>
<%= link_to "Add Employee!", new_employee_url %>

app/views/employees/new.html.erb
<h1>New Employee Details</h1>
<% all_employees = EmployeeProfile.all %>
<%= form_for(@employee, html: {multipart: true}) do |f| %>
	<p>Supervisor</p>
	<label>
		<select name="employee[supervisor_id]">
			<option value=''>None</option>
			<% all_employees.each do |emp| %>
				<% if @employee.supervisor == emp.employee %>			
					<option value=<%= emp.id %> selected><%=emp.name%></option>
				<% else %>
					<option value=<%= emp.id %>><%=emp.name%></option>
				<% end %>
			<% end %>
		</select>
	</label>

	<h4>Part of the following teams</h4>
	<% Team.all.each do |team| %>
		<label>
			<%= team.name %>
			<% if @employee.teams.include?(team) %>
				<input type="checkbox" name="employee[team_ids][]" value=<%= team.id %> checked>
			<% else %>
				<input type="checkbox" name="employee[team_ids][]" value=<%= team.id %> >
			<% end %>
		</label>
		<label> Team Leader
			<% if @employee.supervised_teams.include?(team) %>
				<input type="checkbox" name="employee[supervised_team_ids][]" value=<%= team.id %> checked>
			<% else %>
				<input type="checkbox" name="employee[supervised_team_ids][]" value=<%= team.id %>>
			<% end %>
		</label>
		<br><br>
	<% end %>

	<br><br>
	<label>
		Name
		<input type="text" name="employee[employee_profile_attributes][name]" value=<%= @employee.employee_profile.name %>>
	</label>

	<br><br>
	<label>
		E-mail
		<input type="text" name="employee[employee_profile_attributes][email]" value=<%= @employee.employee_profile.email %>>
	</label>

	<br><br>
	<label>
		Position
		<input type="text" name="employee[employee_profile_attributes][position]" value=<%= @employee.employee_profile.position %>>
	</label>

	<br><br>
	<label>
		Salary
		<input type="number" name="employee[employee_profile_attributes][salary]" value=<%= @employee.employee_profile.salary %>>
	</label>

	<br><br>
	<label>
		Height
		<input type="number" name="employee[employee_profile_attributes][height]" value=<%= @employee.employee_profile.height %>>
	</label>

	<br><br>
	<label>
		Favorite Food
		<input type="text" name="employee[employee_profile_attributes][favorite_food]" value=<%= @employee.employee_profile.favorite_food %>>
	</label>

	<br><br>
	<label>
		Favorite Day
		<input type="text" name="employee[employee_profile_attributes][favorite_day]" value=<%= @employee.employee_profile.favorite_day %>>
	</label>

	<br><br>
	<label>
		Age
		<input type="number" name="employee[employee_profile_attributes][age]" value=<%= @employee.employee_profile.age %>>
	</label>

	<br><br>
	
	<%= f.fields_for(:employee_profile) do |profile_form| %>
		<%=profile_form.label :birth_date %>
		<%=profile_form.date_select :birth_date, value: @employee.employee_profile.birth_date %>

		<br><br>
	 	<%= profile_form.label :photo, "Attach a Photo" %><br />
	  	<%= profile_form.file_field :photo %>
	<% end %>
	<br><br>

	<%=f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppEmployee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul>
	<% unless flash[:errors].nil? %>
		<% flash[:errors].each do |err| %>
			<li><%= err %></li>
		<% end %>
	<% end %>
</ul>
<%= flash[:success] %>
<%= yield %>

<br><br>
Nav 
<%=link_to "Home", root_url %>
<%=link_to "Teams", teams_url %>
</body>
</html>